AWSTemplateFormatVersion: '2010-09-09'
Description: >
  managingstack:
  - VPC with public/private subnets, IGW, NAT Gateway, VPC endpoints (S3, DynamoDB)
  - Security groups for bastion, ALB, web servers, RDS, Lambda
  - EC2 instances (bastion, web servers, AD, file server)
  - ALB + NLB with listeners/target groups
  - RDS VPC prerequisites (DB Subnet Group) + DynamoDB table
  - S3 bucket
  - Lambda (LabRole hardcoded, unchanged)
  - API Gateway integrated with Lambda

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
  PublicSubnet1Cidr:
    Type: String
    Default: 10.0.1.0/24
  PublicSubnet2Cidr:
    Type: String
    Default: 10.0.2.0/24
  PrivateSubnet1Cidr:
    Type: String
    Default: 10.0.10.0/24
  PrivateSubnet2Cidr:
    Type: String
    Default: 10.0.20.0/24
  LambdaTimeout:
    Type: Number
    Default: 30
  LambdaMemory:
    Type: Number
    Default: 256

Resources:

  ### VPC + Subnets + Routing
  ManageVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ManageVPC
      CidrBlock: !Ref PublicSubnet1Cidr
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ManageVPC
      CidrBlock: !Ref PublicSubnet2Cidr
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [1, !GetAZs '']

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ManageVPC
      CidrBlock: !Ref PrivateSubnet1Cidr
      AvailabilityZone: !Select [0, !GetAZs '']

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ManageVPC
      CidrBlock: !Ref PrivateSubnet2Cidr
      AvailabilityZone: !Select [1, !GetAZs '']

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref ManageVPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ManageVPC

  PublicDefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  NatEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatEip.AllocationId
      SubnetId: !Ref PublicSubnet1

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ManageVPC

  PrivateDefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable

  ### VPC Endpoints
  S3GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref ManageVPC
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      RouteTableIds:
        - !Ref PublicRouteTable
        - !Ref PrivateRouteTable
      VpcEndpointType: Gateway

  DynamoDbGatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref ManageVPC
      ServiceName: !Sub com.amazonaws.${AWS::Region}.dynamodb
      RouteTableIds:
        - !Ref PublicRouteTable
        - !Ref PrivateRouteTable
      VpcEndpointType: Gateway

  ### Security Groups
  BastionSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH access
      VpcId: !Ref ManageVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  ALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Public HTTP
      VpcId: !Ref ManageVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: HTTP and SSH
      VpcId: !Ref ManageVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSG
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref BastionSG

  RDSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: MySQL access
      VpcId: !Ref ManageVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref WebSG

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda
      VpcId: !Ref ManageVPC
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  ### EC2 Instances
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: vockey
      ImageId: ami-0a5c3558529277641
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds:
        - !Ref BastionSG

  WebServer1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: vockey
      ImageId: ami-0a5c3558529277641
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds:
        - !Ref WebSG

  WebServer2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: vockey
      ImageId: ami-0a5c3558529277641
      SubnetId: !Ref PublicSubnet2
      SecurityGroupIds:
        - !Ref WebSG

  ADServer1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      KeyName: vockey
      ImageId: ami-0a5c3558529277641
      SubnetId: !Ref PrivateSubnet1

  FileServer1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      KeyName: vockey
      ImageId: ami-0a5c3558529277641

  ### S3 Bucket (referenced by Lambda)
  PoCS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  ### DynamoDB Table
  PoCDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PoCLogs
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  ### Lambda Function
  PoCLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: PoC-Handler
      Runtime: nodejs18.x
      Handler: index.handler
      Role: arn:aws:iam::690471439659:role/LabRole
      Timeout: !Ref LambdaTimeout
      MemorySize: !Ref LambdaMemory
      VpcConfig:
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
      Environment:
        Variables:
          S3_BUCKET: !Ref PoCS3Bucket
          DDB_TABLE: !GetAtt PoCDynamoTable.TableName
      Code:
        ZipFile: |
          const AWS = require('aws-sdk');
          const ddb = new AWS.DynamoDB.DocumentClient();
          const s3 = new AWS.S3();
          exports.handler = async (event) => {
            const now = new Date().toISOString();
            const payload = event.body ? JSON.parse(event.body) : { msg: 'test' };
            const item = { pk: 'pocevent', sk: now, payload };
            await ddb.put({ TableName: process.env.DDB_TABLE, Item: item }).promise();
            await s3.putObject({
              Bucket: process.env.S3_BUCKET,
              Key: `pocevents/${now}.json`,
              Body: JSON.stringify(item),
              ContentType: 'application/json'
            }).promise();
            return { statusCode: 200, body: JSON.stringify({ message: 'OK', time: now }) };
          };

  ### RDS VPC prerequisites (no DB instance)
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS instances
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      Tags:
        - Key: Name
          Value: PoC-RDS-SubnetGroup

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref ManageVPC
  RDSSubnetGroupName:
    Description: Name of the RDS DB Subnet Group
    Value: !Ref RDSSubnetGroup
  DynamoDBTableName:
    Description: DynamoDB table name
    Value: !GetAtt PoCDynamoTable.TableName
  S3BucketName:
    Description: S3 bucket name
    Value: !Ref PoCS3Bucket
  LambdaName:
    Description: Lambda function name
    Value: !Ref PoCLambdaFunction
